using System;
using System.Collections.Generic;
using System.IO;
using System.Windows.Forms;
using System.Text;

namespace CrawlStats
{
    class CrawlCharacterList : List<CrawlCharacter>

    {
        public CrawlCharacterList()
        {
        }

        public CrawlCharacterList(string dir)
        {
            AddDirectory(dir);
        }

        public void AddDirectory(string dir)
        {
            try
            {
                string[] dirs = Directory.GetDirectories(dir);
                foreach (string d in dirs)
                    AddDirectory(d);
                string[] files = Directory.GetFiles(dir, "logfile");
                foreach (string f in files)
                {
                    if (dir.IndexOf("saves") == -1)
                    {
                        CrawlCharacter c = new CrawlCharacter(f);
                        Add(c);
                        Application.DoEvents();                       
                    }
                }
            }
            catch { }
        }

        public string ToHTML()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine(
@"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">
<html>
	<head>
		<title>Trinkit's Dungeon Crawl Archives</title>
		<link rel=""stylesheet"" type=""text/css"" media=""all"" href=""clhtml/style.css"" />
		<script type=""text/javascript"" src=""clhtml/scriptaculous/lib/prototype.js""></script>
		<script type=""text/javascript"" src=""clhtml/fastinit.js""></script>
		<script type=""text/javascript"" src=""clhtml/tablesort.js""></script>	
	</head>
	<body>
			<table class=""sortable"" width=""100%"">
			<thead>
			<tr><th>Version</th><th>Name</th><th>Level</th><th>Race</th><th>Class</th><th>Turns</th><th class=""sortfirstdesc"">Score</th><th class=""nosort"">Chardump</th><th class=""nosort"">Replay</th></tr>
			</thead>
			<tfoot>
			<tr><th colspan=""100%"">This website is generated by <a id=""ad"" href=""http://crawlarchive.com/CrawlLauncher.zip"">CrawlLauncher</a> v2.0.0</th></tr>
			</tfoot>
			<tbody>");
            foreach (CrawlCharacter c in this)
            {
                sb.AppendLine(c.ToHTML());
            }
            string ret = sb.ToString();
            return ret;
        }
    }
}
