using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Net;
using System.Text;
using System.Web;
using System.Windows.Forms;

namespace CrawlArchive
{
    public partial class Form1 : Form
    {
        private List<CrawlCharacter> CrawlList = new List<CrawlCharacter>();
        public Form1()
        {
            InitializeComponent();
        }

        private void btnBrowse_Click(object sender, EventArgs e)
        {
            DialogResult dr = fbdCrawlDir.ShowDialog();
            if (dr != DialogResult.Cancel)
            {
                txtCrawlDir.Text = fbdCrawlDir.SelectedPath.ToString();
                dgCrawl.Rows.Clear();
                Parse(txtCrawlDir.Text);
            }
        }

        private void btnUpload_Click(object sender, EventArgs e)
        {
            foreach (CrawlCharacter c in CrawlList)
            {              
                try
                {
                    HttpWebRequest req = (HttpWebRequest)HttpWebRequest.Create("http://trinkit.crawlarchive.com/" + c.Morgue);
                    HttpWebResponse res = (HttpWebResponse)req.GetResponse();
                    res.Close();
                }
                catch (WebException we)
                {
                    UploadMorgue(c);
                }
                try
                {
                    HttpWebRequest req = (HttpWebRequest)HttpWebRequest.Create("http://trinkit.crawlarchive.com/" + c.Download);
                    HttpWebResponse res = (HttpWebResponse)req.GetResponse();
                    res.Close();
                }
                catch (WebException we)
                {
                    UploadDownload(c);
                }
            }
            UploadIndex();
        }
        private void UploadIndex()
        {
        }

        private void UploadDownload(CrawlCharacter c)
        {
        }

        private void UploadMorgue(CrawlCharacter c)
        {
            FtpWebRequest req = (FtpWebRequest)WebRequest.Create("ftp://trinkit.crawlarchive.com/" + c.Morgue);
            req.Method = WebRequestMethods.Ftp.UploadFile;
            req.Credentials = new NetworkCredential("trinkit", "s9zaPE9ute");
            StreamReader sr = new StreamReader(c.MorgueFile);
            byte[] fc = Encoding.UTF8.GetBytes(sr.ReadToEnd());
            sr.Close();
            req.ContentLength = fc.Length;

            Stream sreq = req.GetRequestStream();
            sreq.Write(fc, 0, fc.Length);
            sreq.Close();
            FtpWebResponse res = (FtpWebResponse)req.GetResponse();
            MessageBox.Show("Upload Complete, status {0}", res.StatusDescription);
            res.Close();
        }

        private void Parse(string dir)
        {
            string[] dirs = Directory.GetDirectories(dir);
            foreach (string d in dirs)
                Parse(d);
            string[] files = Directory.GetFiles(dir, "logfile");
            foreach (string f in files)
            {
                if (dir.IndexOf("saves") == -1)
                {
                    CrawlCharacter c = new CrawlCharacter(f);
                    CrawlList.Add(c);
                    object[] row = new object[7];
                    row[0] = c["v"];
                    row[1] = c["name"];
                    row[2] = Convert.ToInt32(c["xl"]);
                    row[3] = c["race"];
                    row[4] = c["cls"];
                    row[5] = Convert.ToInt32(c["turn"]);
                    row[6] = Convert.ToInt32(c["sc"]);
                    dgCrawl.Rows.Add(row);
                    Application.DoEvents();
                }
            }
        }

        private void btnExport_Click(object sender, EventArgs e)
        {
            btnExport.Enabled = false;
            Application.DoEvents();
            StreamWriter sw = new StreamWriter("Index.html");
            sw.WriteLine(@"
<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">
<html>
	<head>
		<title>Trinkit's Dungeon Crawl Archives</title>
		<link rel=""stylesheet"" type=""text/css"" media=""all"" href=""clhtml/style.css"" />
		<script type=""text/javascript"" src=""clhtml/scriptaculous/lib/prototype.js""></script>
		<script type=""text/javascript"" src=""clhtml/fastinit.js""></script>
		<script type=""text/javascript"" src=""clhtml/tablesort.js""></script>	
	</head>
	<body>
			<table class=""sortable"" width=""100%"">
			<thead>
			<tr><th>Version</th><th>Name</th><th>Level</th><th>Race</th><th>Class</th><th>Turns</th><th class=""sortfirstdesc"">Score</th><th class=""nosort"">Chardump</th><th class=""nosort"">Replay</th></tr>
			</thead>
			<tfoot>
			<tr><th colspan=""100%"">This website is generated by <a id=""ad"" href=""http://crawlarchive.com/CrawlLauncher.zip"">CrawlLauncher</a> v2.0.0</th></tr>
			</tfoot>
			<tbody>");
            foreach (CrawlCharacter c in CrawlList)
            {
                sw.WriteLine(c.ToHTML());
                Application.DoEvents();
            }
            sw.Close();
            btnExport.Enabled = true;
            Application.DoEvents();
        }
    }
}